import { API_BASE_URL } from "../config/api";
import { authService } from "./authService";
import { cylinderMasterService } from "./cylinderMasterService";
import { companyMasterService } from "./companyMasterService";
import { contactsService } from "./contactsService";

export interface Cylinder {
  id: number;
  barcode: string;
  cylinder_id?: number;
}

export interface Customer {
  id: number;
  code: string;
  name: string;
  contact: string;
  email: string;
  status: string;
}

export interface Contact {
  id: number;
  company_id: number;
  name: string;
  phone: string;
  email: string;
}

export interface CheckOutRecord {
  id: number;
  company_id: number;
  contact_id: number;
  cylinder_id: number;
  barcode: string;
  cylinder_type: string;
  created_by: number;
  created_at?: string; // Mock field for UI - will be auto-generated by database
}

export interface CylinderCheckOutApiRecord {
  id: number;
  cylinder_id: number;
  company_id: number;
  company_contact_id: number;
  is_returned: boolean;
  returned_at: string | null;
  created_by_id: number;
  created_at: string;
  updated_at: string;
}

const buildAuthHeaders = (): HeadersInit => {
  const token = authService.getAuthState().token;
  return {
    "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
};

let checkOutApiCache: CylinderCheckOutApiRecord[] = [];
let checkOutApiCacheLoaded = false;

export const cylinderCheckOutService = {
  // Fetch all customers (companies) from backend (cached)
  getCustomers: async (force = false): Promise<Customer[]> => {
    const companies = await companyMasterService.fetchCompanies(force);
    // Map Company to Customer interface if needed
    return companies.map((company) => ({
      id: company.id,
      code: company.company_code,
      name: company.company_name,
      contact: company.phone, // or another field if needed
      email: company.email,
      status: company.active ? "Active" : "Inactive",
    }));
  },

  // Fetch all contacts from backend (cached)
  getContacts: async (force = false): Promise<Contact[]> => {
    return await contactsService.fetchContacts(force);
  },

  // Fetch contacts by customer/company ID
  getContactsByCustomer: async (
    companyId: number,
    force = false,
  ): Promise<Contact[]> => {
    const contacts = await contactsService.fetchContacts(force);
    return contacts.filter((contact) => contact.company_id === companyId);
  },

  validateBarcode: (
    barcode: string,
  ): {
    valid: boolean;
    error?: string;
    cylinderData?: any;
    normalizedBarcode?: string;
  } => {
    // Basic validation
    if (!barcode || barcode.trim() === "") {
      return { valid: false, error: "Barcode/Cylinder Number is required" };
    }

    // Normalize barcode to uppercase for validation
    const normalizedBarcode = barcode.trim().toUpperCase();

    if (normalizedBarcode.length < 3) {
      return {
        valid: false,
        error: "Invalid barcode format (minimum 3 characters)",
      };
    }

    // Check if the barcode matches a serial number in Cylinder Master (case-insensitive)
    const cylinder =
      cylinderMasterService.getCylinderByCylinderNumber(normalizedBarcode);

    if (!cylinder) {
      return {
        valid: false,
        error: `Cylinder Number "${normalizedBarcode}" not found in Cylinder Master. Please add it first or check the cylinder number.`,
      };
    }

    // Check if cylinder is active
    if (!cylinder.active) {
      return {
        valid: false,
        error: `Cylinder Number "${normalizedBarcode}" is inactive in Cylinder Master.`,
      };
    }

    // Check cylinder location - only allow check-out from "Clean Cylinder" location
    if (cylinder.location === "Checked Out") {
      return {
        valid: false,
        error: `Cylinder Number "${normalizedBarcode}" is already checked out. Current location: ${cylinder.location}`,
      };
    }

    // Return success with cylinder data and normalized barcode
    return {
      valid: true,
      normalizedBarcode: normalizedBarcode,
      cylinderData: {
        id: cylinder.id,
        cylinder_number: cylinder.cylinder_number,
        cylinder_type: cylinder.cylinder_type,
        location: cylinder.location,
        track_inventory: cylinder.track_inventory,
      },
    };
  },

  validateCheckOut: (
    customerCode: string,
    cylinders: Cylinder[],
  ): { valid: boolean; error?: string } => {
    if (!customerCode || customerCode.trim() === "") {
      return { valid: false, error: "Please select a customer" };
    }
    if (cylinders.length === 0) {
      return { valid: false, error: "Please scan at least one cylinder" };
    }
    return { valid: true };
  },

  printSampleTag: (cylinder: Cylinder): void => {
    const printWindow = window.open("", "", "height=500,width=800");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Natty Gas Lab - ${cylinder.barcode}</title>
            <style>
              @page {
                size: 5in 3in landscape;
                margin: 0.2in;
              }
              body {
                font-family: Arial, sans-serif;
                padding: 10px;
                margin: 0;
                width: 100%;
                box-sizing: border-box;
              }
              .card {
                border: 2px solid #000;
                padding: 12px;
                width: 100%;
                box-sizing: border-box;
              }
              .header {
                text-align: center;
                border-bottom: 2px solid #000;
                padding-bottom: 6px;
                margin-bottom: 10px;
              }
              .header h1 {
                margin: 0;
                font-size: 18px;
                font-weight: bold;
              }
              .form-grid {
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 8px 15px;
              }
              .form-row {
                display: flex;
                align-items: baseline;
              }
              .form-row.full-width {
                grid-column: 1 / -1;
              }
              .label {
                font-size: 10px;
                font-weight: bold;
                margin-right: 5px;
                white-space: nowrap;
              }
              .value {
                flex: 1;
                border-bottom: 1px solid #000;
                min-height: 14px;
                font-size: 10px;
              }
              .unit {
                font-size: 10px;
                margin-left: 5px;
                white-space: nowrap;
              }
              .checkbox-group {
                display: flex;
                gap: 12px;
                margin-left: 5px;
              }
              .checkbox-item {
                display: flex;
                align-items: center;
                gap: 3px;
              }
              .checkbox {
                width: 12px;
                height: 12px;
                border: 1.5px solid #000;
                display: inline-block;
              }
              .checkbox-label {
                font-size: 10px;
              }
              .remarks-value {
                border-bottom: 1px solid #000;
                min-height: 30px;
              }
              @media print {
                body { padding: 0; }
              }
            </style>
          </head>
          <body>
            <div class="card">
              <div class="header">
                <h1>Natty Gas Lab</h1>
              </div>
              
              <div class="form-grid">
                <div class="form-row">
                  <span class="label">Date:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row">
                  <span class="label">Producer:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row">
                  <span class="label">Sampled By:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row">
                  <span class="label">Company:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row">
                  <span class="label">Well Name:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row">
                  <span class="label">Meter #:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row full-width">
                  <span class="label">Sample Type:</span>
                  <div class="checkbox-group">
                    <div class="checkbox-item">
                      <span class="checkbox"></span>
                      <span class="checkbox-label">Spot</span>
                    </div>
                    <div class="checkbox-item">
                      <span class="checkbox"></span>
                      <span class="checkbox-label">Composite</span>
                    </div>
                  </div>
                </div>

                <div class="form-row">
                  <span class="label">Flow Rate:</span>
                  <span class="value"></span>
                  <span class="unit">MCFD</span>
                </div>

                <div class="form-row">
                  <span class="label">Pressure:</span>
                  <span class="value"></span>
                  <span class="unit">PSI</span>
                </div>

                <div class="form-row">
                  <span class="label">Temp:</span>
                  <span class="value"></span>
                  <span class="unit">F</span>
                </div>

                <div class="form-row">
                  <span class="label">Field H2S:</span>
                  <span class="value"></span>
                  <span class="unit">PPM</span>
                </div>

                <div class="form-row full-width">
                  <span class="label">Bottle#:</span>
                  <span class="value"></span>
                </div>

                <div class="form-row full-width">
                  <span class="label">Remarks:</span>
                  <span class="remarks-value value"></span>
                </div>
              </div>
            </div>
            
            <script>
              window.onload = function() {
                window.print();
              }
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  },

  createCheckOutRecord: (
    customerCode: string,
    contact: string,
    cylinders: Cylinder[],
  ): any => {
    return {
      id: `CO-${Date.now()}`,
      customerCode,
      contact,
      cylinders: cylinders.length,
      date: new Date().toISOString(),
      items: cylinders,
    };
  },

  parseBarcode: (barcode: string): { cylinderCode: string; type: string } => {
    // Simple parsing - in real app would have more sophisticated logic
    const parts = barcode.split("-");
    return {
      cylinderCode: parts[0] || barcode.substring(0, 3),
      type: parts[1] || "Standard",
    };
  },

  addCustomer: (customer: Customer): Customer => {
    return customer;
  },

  addContact: (contact: Contact): Contact => {
    return contact;
  },

  fetchCheckOutRecords: async (
    forceRefresh = false,
  ): Promise<CylinderCheckOutApiRecord[]> => {
    if (checkOutApiCacheLoaded && !forceRefresh) {
      return checkOutApiCache;
    }

    const response = await fetch(`${API_BASE_URL}/cylinder_checkout`, {
      method: "GET",
      headers: buildAuthHeaders(),
    });

    if (!response.ok) {
      const message =
        response.status === 401
          ? "Unauthorized"
          : "Failed to load cylinder checkouts";
      throw new Error(message);
    }

    const data = (await response.json()) as CylinderCheckOutApiRecord[];
    checkOutApiCache = data;
    checkOutApiCacheLoaded = true;
    return data;
  },

  isCylinderCheckedOut: async (cylinder_id: number): Promise<boolean> => {
    const records = await cylinderCheckOutService.fetchCheckOutRecords();
    return records.some(
      (record) => record.cylinder_id === cylinder_id && !record.is_returned,
    );
  },

  getActiveCheckOutRecord: async (
    cylinder_id: number,
  ): Promise<CylinderCheckOutApiRecord | undefined> => {
    const records = await cylinderCheckOutService.fetchCheckOutRecords();
    return records.find(
      (record) => record.cylinder_id === cylinder_id && !record.is_returned,
    );
  },

  markCylindersReturned: async (cylinderIds: number[]): Promise<void> => {
    const uniqueIds = Array.from(new Set(cylinderIds.filter(Boolean)));
    if (uniqueIds.length === 0) return;

    const records = await cylinderCheckOutService.fetchCheckOutRecords();
    const pendingRecords = records.filter(
      (record) =>
        uniqueIds.includes(record.cylinder_id) && record.is_returned === false,
    );

    if (pendingRecords.length === 0) return;

    const returnedAt = new Date().toISOString();

    await Promise.all(
      pendingRecords.map(async (record) => {
        const response = await fetch(
          `${API_BASE_URL}/cylinder_checkout/${record.id}`,
          {
            method: "PUT",
            headers: buildAuthHeaders(),
            body: JSON.stringify({
              cylinder_id: record.cylinder_id,
              company_id: record.company_id,
              company_contact_id: record.company_contact_id,
              is_returned: true,
              returned_at: returnedAt,
            }),
          },
        );

        if (!response.ok) {
          const message =
            response.status === 401
              ? "Unauthorized"
              : "Failed to update cylinder checkout status";
          throw new Error(message);
        }
      }),
    );

    checkOutApiCache = checkOutApiCache.map((record) =>
      uniqueIds.includes(record.cylinder_id)
        ? {
            ...record,
            is_returned: true,
            returned_at: record.returned_at ?? returnedAt,
          }
        : record,
    );
    checkOutApiCacheLoaded = true;
  },

  submitCheckOutRecords: async (
    company_id: number,
    contact_id: number,
    cylinders: Cylinder[],
  ): Promise<void> => {
    const payloads = cylinders.map((cylinder) => {
      if (!cylinder.cylinder_id) {
        throw new Error(`Cylinder ID missing for ${cylinder.barcode}`);
      }
      return {
        cylinder_id: cylinder.cylinder_id,
        company_id,
        company_contact_id: contact_id,
        is_returned: false,
      };
    });

    await Promise.all(
      payloads.map(async (payload) => {
        const response = await fetch(`${API_BASE_URL}/cylinder_checkout`, {
          method: "POST",
          headers: buildAuthHeaders(),
          body: JSON.stringify(payload),
        });

        if (!response.ok) {
          const message =
            response.status === 401
              ? "Unauthorized"
              : "Failed to create cylinder checkout";
          throw new Error(message);
        }
      }),
    );

    checkOutApiCacheLoaded = false;
  },

  getCheckOutRecords: (): CheckOutRecord[] => {
    return [];
  },

  getCheckOutById: (id: number): CheckOutRecord | undefined => {
    return undefined;
  },

  getCheckOutsByCompany: (company_id: number): CheckOutRecord[] => {
    return [];
  },

  getCheckOutsByContact: (contact_id: number): CheckOutRecord[] => {
    return [];
  },

  getCheckOutsByBarcode: (barcode: string): CheckOutRecord[] => {
    return [];
  },

  getCustomerById: async (
    id: number,
    force = false,
  ): Promise<Customer | undefined> => {
    const customers = await cylinderCheckOutService.getCustomers(force);
    return customers.find((customer) => customer.id === id);
  },

  getContactById: async (
    id: number,
    force = false,
  ): Promise<Contact | undefined> => {
    const contacts = await contactsService.fetchContacts(force);
    return contacts.find((contact) => contact.id === id);
  },

  validateCheckOutWithIds: (
    companyId: number | null,
    contactId: number | null,
    cylinders: Cylinder[],
  ): { valid: boolean; error?: string } => {
    if (!companyId) {
      return { valid: false, error: "Please select a company" };
    }
    if (!contactId) {
      return { valid: false, error: "Please select a contact" };
    }
    if (cylinders.length === 0) {
      return { valid: false, error: "Please scan at least one cylinder" };
    }
    return { valid: true };
  },
};
